version: "3.8"

services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    environment:
      APP_URL: 'http://localhost:3000'
      NODE_ENV: production
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
